export const tracks = [
  { id:0, title:"If The Sun Burns Out Tonight", artist:"VALORANT, Grabbitz, Oli Sykes, Courtney LaPlante", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/01/cover.jpg", src:"assets/01/If_The_Sun_Burns_Out_Tonight-VALORANT.mp3", lyrics:"assets/01/If_The_Sun_Burns_Out_Tonight-VALORANT.lrc", sourceUrl:"https://open.spotify.com/album/30wcEnAwWs8vMajB23SPx5" },
  { id:1, title:"superHuman", artist:"AUDREY NUNA, VALORANT", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/02/cover.jpg", src:"assets/02/superHuman-Audrey Nuna,VALORANT.mp3", lyrics:"assets/02/superHuman-Audrey Nuna,VALORANT.lrc", sourceUrl:"https://open.spotify.com/album/3BfiwgwqmGt5JYZLGtLA1b" },
  { id:2, title:"Ticking Away", artist:"VALORANT, Grabbitz, bbno$", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/03/cover.jpg", src:"assets/03/Ticking Away-VALORANT,Grabbitz,bbno$.mp3", lyrics:"assets/03/Ticking Away-VALORANT,Grabbitz,bbno$.lrc", sourceUrl:"https://open.spotify.com/album/2CNm7QxoOSkqawLMnoepZB" },
  { id:3, title:"Die For You", artist:"VALORANT, Grabbitz", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/04/cover.jpg", src:"assets/04/Die For You-VALORANT,Grabbitz.mp3", lyrics:"assets/04/Die For You-VALORANT,Grabbitz.lrc", sourceUrl:"https://open.spotify.com/album/5KWBx45fX3EKtpeJ2zF5p2" },
  { id:4, title:"SUPERPOWER", artist:"VALORANT, KISS OF LIFE, Mark Tuan", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/05/cover.jpg", src:"assets/05/SUPERPOWER-VALORANT,KISS OF LIFE,段宜恩.mp3", lyrics:"assets/05/SUPERPOWER-VALORANT,KISS OF LIFE,段宜恩.lrc", sourceUrl:"https://open.spotify.com/track/7adlbYpN7XNzgCMOO35671" },
  { id:5, title:"RUN!", artist:"VALORANT, Odetari, Lay Bankz", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/06/cover.jpg", src:"assets/06/RUN! (feat. Lay Bankz)-VALORANT,Odetari,Lay Bankz.mp3", lyrics:"assets/06/RUN! (feat. Lay Bankz)-VALORANT,Odetari,Lay Bankz.lrc", sourceUrl:"https://open.spotify.com/album/2xZzXPedzddYGOzhRpIzvH" },
  { id:6, title:"2WORLDS", artist:"VALORANT, Madge", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/07/cover.jpg", src:"assets/07/2WORLDS-VALORANT,Madge.mp3", lyrics:"assets/07/2WORLDS-VALORANT,Madge.lrc", sourceUrl:"https://open.spotify.com/track/0MoTvVdhu4Ocm2Y7yphxPh" },
  { id:7, title:">one (greater than one)", artist:"VALORANT, ericdoa", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/08/cover.jpg", src:"assets/08/greater than one-VALORANT,ericdoa.mp3", lyrics:"assets/08/greater than one-VALORANT,ericdoa.lrc", sourceUrl:"https://open.spotify.com/album/6GLcfMMmFXrfk9ydAjeLop" },
  { id:8, title:"RAJA", artist:"ARB4, Tienas, Mangal Suvarnan, VALORANT", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/09/cover.jpg", src:"assets/09/RAJA-ARB4,Tienas,Mangal Suvarnan,VALORANT.mp3", lyrics:"assets/09/RAJA-ARB4,Tienas,Mangal Suvarnan,VALORANT.lrc", sourceUrl:"https://open.spotify.com/album/0PcI65mHvmN6b6vLjb0dek" },
  { id:9, title:"Fire Again", artist:"VALORANT, Ashnikko", album:"VALORANT Original Music", genre:"VALORANT", cover:"assets/10/cover.jpg", src:"assets/10/Fire Again-VALORANT,Ashnikko.mp3", lyrics:"assets/10/Fire Again-VALORANT,Ashnikko.lrc", sourceUrl:"https://music.apple.com/us/album/fire-again-feat-ashnikko-single/1833384524" },
  { id:10, title:"M.I.A", artist:"KATSEYE, VALORANT", album:"VALORANT Game Changers Version", genre:"VALORANT", cover:"assets/11/cover.jpg", src:"assets/11/M.I.A (VALORANT Game Changers Version)-KATSEYE,VALORANT (1).mp3", lyrics:"assets/11/M.I.A (VALORANT Game Changers Version)-KATSEYE,VALORANT (1).lrc", sourceUrl:"https://open.spotify.com/track/0VodPyDs7Uw9UpeRp22vq6" },
  { id:11, title:"登神 (GODS)", artist:"Noli", album:"GODS · 翻唱版", genre:"英雄联盟", cover:"assets/12/cover.jpg", src:"assets/12/登神(GODS)-noli.mp3", lyrics:"assets/12/登神(GODS)-noli.lrc", sourceUrl:"https://www.bilibili.com/video/BV1M34y1G7YH/" },
  { id:12, title:"STAR WALKIN'（逐星）", artist:"唐丹岚", album:"Worlds 2022 · 中文翻唱", genre:"英雄联盟", cover:"assets/13/cover.jpg", src:"assets/13/STAR WALKIN'（逐星）（Cover：Lil Nas X、英雄联盟S12主题曲）-唐丹岚.mp3", lyrics:"assets/13/STAR WALKIN'（逐星）（Cover：Lil Nas X、英雄联盟S12主题曲）-唐丹岚.lrc", sourceUrl:"https://www.bilibili.com/video/BV1R84y1i7s2/" },
  { id:13, title:"Burn It All Down", artist:"League of Legends, Denzel Curry, PVRIS", album:"Denzel Curry Remix", genre:"英雄联盟", cover:"assets/14/cover.jpg", src:"assets/14/Burn It All Down (Denzel Curry Remix)-英雄联盟,Denzel Curry,PVRIS.mp3", lyrics:"assets/14/Burn It All Down (Denzel Curry Remix)-英雄联盟,Denzel Curry,PVRIS.lrc", sourceUrl:"https://open.spotify.com/album/3SDmDz6RgolGmiUtgooCvv" },
  { id:14, title:"Take Over", artist:"League of Legends, Jeremy McKinnon, MAX, Henry Lau", album:"Worlds 2020", genre:"英雄联盟", cover:"assets/15/cover.jpg", src:"assets/15/Take Over-英雄联盟,Jeremy McKinnon,MAX,HENRY刘宪华.mp3", lyrics:"assets/15/Take Over-英雄联盟,Jeremy McKinnon,MAX,HENRY刘宪华.lrc", sourceUrl:"https://open.spotify.com/album/746kCUpkRofCTYBupy2grd" },
  { id:15, title:"Phoenix", artist:"League of Legends, Cailin Russo, Chrissy Costanza", album:"Worlds 2019", genre:"英雄联盟", cover:"assets/16/cover.jpg", src:"assets/16/Phoenix-英雄联盟,Cailin Russo,Chrissy Costanza.mp3", lyrics:"assets/16/Phoenix-英雄联盟,Cailin Russo,Chrissy Costanza.lrc", sourceUrl:"https://open.spotify.com/album/1roYiEGA7UXqYWFwhUR0UM" },
  { id:16, title:"RISE (instrumental)", artist:"Mako, The Word Alive, The Glitch Mob", album:"Worlds 2018", genre:"英雄联盟", cover:"assets/17/cover.jpg", src:"assets/17/RISE (instrumental)-Mako,The Word Alive,The Glitch Mob.mp3", lyrics:"assets/17/RISE (instrumental)-Mako,The Word Alive,The Glitch Mob.lrc", sourceUrl:"https://open.spotify.com/album/4bpSYIKaoI5AXkA48iNRSx" },
  { id:17, title:"Legends Never Die", artist:"League of Legends, Against The Current", album:"Worlds 2017", genre:"英雄联盟", cover:"assets/18/cover.jpg", src:"assets/18/Legends Never Die-英雄联盟,Against the Current.mp3", lyrics:"assets/18/Legends Never Die-英雄联盟,Against the Current.lrc", sourceUrl:"https://open.spotify.com/album/3YsV3Mh57qUXomaiVC1EU6" },
  { id:18, title:"Ignite (cloudfield Bootleg)", artist:"cloudfield, Zedd", album:"Worlds 2016 · Bootleg", genre:"英雄联盟", cover:"assets/19/cover.jpg", src:"assets/19/Ignite (cloudfield Bootleg)-cloudfield,Zedd.mp3", lyrics:"assets/19/Ignite (cloudfield Bootleg)-cloudfield,Zedd.lrc", sourceUrl:"https://soundcloud.com/cloudfieldmusic/zedd-ignite-cloudfield-bootleg" }
].map(track => ({...track, note:`${track.title} · ${track.artist}。当前页面使用 assets 目录中的完整本地音源、对应封面和同步歌词。`}));

